version: '3'
services: 
    sentinel1:
        container_name: redis-sentinel1
        build: 
            context: .
            args:
            - REDIS_PORT=26379
        volumes: 
            - ./data/redis-sentinel1/data:/data
        ports: 
        - 26379:26379               
    sentinel2:
        container_name: redis-sentinel2
        build:
            context: .
            args: 
            - REDIS_PORT=26380
        volumes: 
            - ./data/redis-sentinel2/data:/data
        ports: 
        - 26380:26380
    sentinel3:
        container_name: redis-sentinel3
        build: 
            context: .
            args: 
            - REDIS_PORT=26381
        volumes: 
            - ./data/redis-sentinel3/data:/data
        ports: 
        - 26381:26380
networks: 
    default:
        external: 
            name: master-slave_default
