version: '3'
services: 
    node1:
        container_name: redis-node1
        build: 
            context: redis
            args:
            - REDIS_PORT=9001
        networks:
            fwa_network:
                ipv4_address: 172.20.0.2

    node2:
        container_name: redis-node2
        build: 
            context: redis
            args:
            - REDIS_PORT=9002
        networks:
            fwa_network:
                ipv4_address: 172.20.0.3
    node3:
        container_name: redis-node3
        build: 
            context: redis
            args:
            - REDIS_PORT=9003
        networks:
            fwa_network:
                ipv4_address: 172.20.0.4
    node4:
        container_name: redis-node4
        build: 
            context: redis
            args:
            - REDIS_PORT=9004
        networks:
            fwa_network:
                ipv4_address: 172.20.0.5
    node5:
        container_name: redis-node5
        build: 
            context: redis
            args:
            - REDIS_PORT=9005
        networks:
            fwa_network:
                ipv4_address: 172.20.0.6
    node6:
        container_name: redis-node6
        build: 
            context: redis
            args:
            - REDIS_PORT=9006
        networks:
            fwa_network:
                ipv4_address: 172.20.0.7
    cluster-creator:
        image: redis
        container_name: redis-cluster-creator
        entrypoint: redis-cli --cluster create 172.20.0.2:9001 172.20.0.3:9002 172.20.0.4:9003 172.20.0.5:9004 172.20.0.6:9005 172.20.0.7:9006 --cluster-replicas 1 --cluster-yes
        networks:
            fwa_network:
        depends_on: 
        - node1
        - node2
        - node3
        - node4
        - node5
        - node6
networks:
  fwa_network:
    driver: bridge
    name: fwa_network
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1